version: '3'

services:
  redis-server:
    container_name: 'redis-server'
    image: 'redis'
    ports:
      - "6379:6379"
  backend-app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure